# Common URLs
HOME = 'https://www.instagram.com/'
HASHTAG = f'{HOME}explore/tags/'

# Text constants
FOLLOW_TEXT = 'Follow'

# Tag indexes
FIRST_HASHTAG_A = 6
FIRST_RECENT_HASHTAG_A = 15
LIKE_BUTTON_SVG = 8
COMMENT_BUTTON_SVG = 10
COMMENT_BUTTON_SVG_FALLBACK = 11
COMMENT_TEXTAREA = 0

# Timeouts/delays
TIMEOUT = 30
TEXTAREA_TIMEOUT = TIMEOUT / 5
DELAY = TIMEOUT / 10

# Window size
WIDTH = 375
HEIGHT = 1000

MAX_FOLLOWS_PER_POST = 10